export const interests = [
  'Travel and Adventure',
  'Music',
  'Food and Cooking',
  'Sports and Fitness',
  'Technology and Gadgets',
  'Reading and Literature',
  'Gaming and eSports',
  'Movies and Television',
  'Art and Culture',
  'Nature and Environment',
  'Science and Space',
  'Fashion and Beauty',
  'Photography and Videography',
  'Social Media and Blogging',
  'Health and Wellness',
  'Business and Entrepreneurship',
]
